-- Ejecuta este archivo DESPUÉS de schema.sql (datos de ejemplo de proyectos)
SET NAMES utf8mb4;
INSERT INTO proyecto (titulo, fecha, anio, resumen, descripcion, imagen, fotos, video, etiqueta, color, emoji) VALUES
('Regalando Sonrisas con Family Love - Huancayo', '09 febrero 2025', 2024, 'En nuestra 2da Campaña Navideña 2024, Family Love llevó el espíritu navideño a las calles de Huancayo, compartiendo momentos de alegría, esperanza y solidaridad con familias en situación de vulnerabilidad.', 'En nuestra 2da Campaña Navideña 2024, realizada el pasado 23 de diciembre, Family Love llevó el espíritu navideño a las calles de Huancayo, compartiendo momentos de alegría, esperanza y solidaridad con familias en situación de vulnerabilidad.

Durante esta jornada especial, entregamos alimentos, ropa y juguetes a niños, adultos y adultos mayores, brindando no solo abrigo y sustento, sino también abrazos, sonrisas y palabras de aliento.

Conscientes de la difícil situación que enfrentan muchos ancianos en nuestra comunidad, nos aseguramos de que recibieran una canasta de alimentos básicos, llevándoles un poco de tranquilidad y bienestar en estas fechas especiales.

Ver la felicidad en los rostros de los niños al recibir un juguete, la gratitud de los adultos al recibir ropa abrigadora y la emoción de los ancianos al recibir compañía y alimentos, fue el mayor regalo de todos.

Nada de esto habría sido posible sin el esfuerzo y dedicación de nuestros voluntarios, auspiciadores y donantes. Juntos demostramos que un pequeño gesto puede transformar vidas.', '/images/hero-images/h2.webp', '["/images/hero-images/imagen1.jpg", "/images/hero-images/imagen2.jpg", "/images/hero-images/imagen3.jpg"]', '/images/hero-images/video1.mp4', 'Campaña Navideña', 'from-rose-500 to-red-600', '🎄'),
('Campaña Navideña en Ullusca – 2024', '20 diciembre 2024', 2024, 'La magia de la Navidad iluminó el centro poblado de Ullusca y sus cuatro barrios gracias al esfuerzo y compromiso de Family Love.', 'La magia de la Navidad iluminó el centro poblado de Ullusca y sus cuatro barrios: Barrio Centro, Huaylas, Barranco y Retamayo, gracias al esfuerzo y compromiso de Family Love.

Esta campaña navideña reunió a voluntarios comprometidos que llevaron alegría, esperanza y apoyo a las familias más necesitadas de la comunidad. Durante la jornada, realizamos actividades recreativas, dinámicas para niños y adultos, entrega de regalos, donaciones, chocolatada y momentos llenos de amor y unión.

Nada de esto habría sido posible sin el valioso apoyo de nuestros voluntarios, auspiciadores y donantes, cuyo esfuerzo y generosidad marcaron la diferencia en muchas vidas.

Queremos hacer un reconocimiento especial a nuestros auspiciadores: I.E.P. San Antonio María Claret, Dr. Alex Sinche y el Diario Primicia, por su invaluable respaldo y confianza en nuestra labor.', '/images/hero-images/family love ullusca footo-67.webp', '["/images/hero-images/ullusca navidad-2024-1.jpg", "/images/hero-images/ullusca navidad-2024-2.jpg", "/images/hero-images/ullusca navidad-2024-3.jpg", "/images/hero-images/ullusca navidad-2024-4.jpg"]', '/images/videos/video-ullusca navidad-2024-1.mp4', 'Campaña Navideña', 'from-blue-500 to-indigo-600', '⭐'),
('Renovando Estilo y Sonrisa', '29 octubre 2024', 2024, 'La Asociación FAMILY LOVE, en colaboración con el Salón de Belleza Romy\'s y el CAM EsSalud, llevó a cabo una jornada especial en el Centro del Adulto Mayor Concepción.', 'La Asociación FAMILY LOVE, en colaboración con el Salón de Belleza Romy\'s y el CAM EsSalud, llevó a cabo una jornada especial el 29 de octubre en el Centro del Adulto Mayor Concepción.

Este evento combinó dos experiencias transformadoras: corte de cabello y risoterapia, brindando a los adultos mayores un espacio de renovación y bienestar.

A través de esta iniciativa, no solo realzamos la autoestima de nuestros adultos mayores, sino que también fomentamos en los futuros médicos el desarrollo de habilidades blandas como la empatía y la comunicación.

En FAMILY LOVE, seguimos apostando por actividades que generen impacto positivo y fortalezcan el lazo entre generaciones.', '/images/hero-images/2 foto family-9.webp', '["/images/hero-images/renovacion.jpeg", "/images/hero-images/renovacion.webp", "/images/hero-images/renovacion1.webp"]', NULL, 'Bienestar Social', 'from-purple-500 to-pink-600', '💜'),
('Taller de Risoterapia para Adultos Mayores – ONP', '18 octubre 2024', 2024, 'La Asociación FAMILY LOVE realizó un exitoso Taller de Risoterapia en la Casa del Pensionista Yuyaq - Huancayo, promoviendo la risa como herramienta para mejorar la salud.', 'El 18 de octubre de 2024, la Asociación FAMILY LOVE realizó un exitoso Taller de Risoterapia en la Casa del Pensionista Yuyaq - Huancayo, gracias a la invitación de la ONP.

Este evento reunió a adultos mayores y estudiantes de medicina que también son clowns hospitalarios, promoviendo la risa como una herramienta para mejorar la salud física y emocional.

A través de dinámicas de clown y ejercicios de risoterapia, los adultos mayores experimentaron momentos de alegría y conexión, reduciendo el estrés y fortaleciendo su bienestar.

En FAMILY LOVE, seguimos comprometidos con iniciativas que transformen vidas y fortalezcan el vínculo entre generaciones a través del poder de la risa y la solidaridad.', '/images/hero-images/ONP-1.jpg', '["/images/hero-images/ONP-1.jpg", "/images/hero-images/ONP-2.jpg", "/images/hero-images/ONP-3.jpg", "/images/hero-images/ONP-4.jpg", "/images/hero-images/ONP-5.jpg"]', NULL, 'Salud y Bienestar', 'from-emerald-500 to-teal-600', '😄'),
('Repartiendo Sonrisas y Sueños – CAR Virgen de Lourdes', '01 marzo 2025', 2025, 'Los voluntarios de Family Love llevaron a cabo una jornada solidaria en el CAR Virgen de Lourdes en Jauja, brindando bienestar emocional y recreación a los niños del albergue.', 'En el marco de sus acciones de responsabilidad social, los voluntarios de Family Love llevaron a cabo una jornada solidaria en el CAR Virgen de Lourdes, con el objetivo de brindar bienestar emocional y espacios de recreación a los niños del albergue.

La actividad, denominada "Repartiendo sonrisas y sueños", incluyó dinámicas de clown comunitario y la entrega de obsequios preparados con especial dedicación. Estas acciones permitieron generar un ambiente de alegría, confianza y cercanía, promoviendo valores como la solidaridad, el respeto y la empatía.

A través de esta intervención, Family Love reafirma su compromiso institucional con el desarrollo integral de la niñez y la promoción de iniciativas que contribuyan positivamente al bienestar de las poblaciones en situación de vulnerabilidad.', '/images/hero-images/h2.webp', '["/images/hero-images/h2.webp", "/images/hero-images/Repartiendosonrisa01.jpg", "/images/hero-images/Repartiendosonrisa02.jpg", "/images/hero-images/Repartiendosonrisa03.jpg", "/images/hero-images/Repartiendosonrisa04.jpg", "/images/hero-images/Repartiendosonrisa05.jpg", "/images/hero-images/Repartiendosonrisa06.jpg", "/images/hero-images/Repartiendosonrisa07.jpg", "/images/hero-images/Repartiendosonrisa08.jpg", "/images/hero-images/Repartiendosonrisa09.jpg", "/images/hero-images/Repartiendosonrisa10.jpg"]', '/images/videos/Repartiendosonrisa01.mp4', 'Jornada Solidaria', 'from-orange-400 to-rose-500', '🤡'),
('Celebrando la Fuerza Femenina: Voces que Inspiran', '08 marzo 2025', 2025, 'Family Love participó en la campaña por el Día Internacional de la Mujer en Matahuasi, con intervenciones artísticas del equipo Elo Clown llevando alegría y reconocimiento.', 'En el marco de las actividades conmemorativas por el Día Internacional de la Mujer, Family Love participó en la campaña "Celebrando la Fuerza Femenina: Voces que Inspiran", organizada por la organización sin fines de lucro Alza tu Voz, en coordinación con la Municipalidad de Matahuasi.

Durante la jornada, el equipo de Elo Clown de Family Love se sumó a las actividades con intervenciones artísticas orientadas a llevar mensajes de alegría, reconocimiento y emoción, resaltando el valor, la fortaleza y el rol fundamental de las mujeres en la sociedad.

La participación en esta campaña reafirma el compromiso institucional de Family Love con la promoción de valores de igualdad, respeto y empoderamiento, así como con el trabajo articulado junto a organizaciones y autoridades locales para generar impacto positivo en la comunidad.', '/images/hero-images/voces q inspiran.jpg', '["/images/hero-images/voces q inspiran.jpg"]', NULL, 'Día de la Mujer', 'from-pink-400 to-purple-500', '💜'),
('Taller "Museo de Recuerdos" – CAM Concepción', '23 mayo 2025', 2025, 'Family Love llevó a cabo el taller psicosocial Museo de Recuerdos en el CAM Concepción, promoviendo la integración y el bienestar emocional de las personas mayores.', 'Family Love llevó a cabo el taller psicosocial "Museo de Recuerdos" en el CAM Concepción, con el propósito de promover la integración, la memoria activa y el bienestar emocional de las personas mayores.

Durante la jornada, los participantes compartieron historias de vida, experiencias significativas y recuerdos que forman parte de su identidad personal y colectiva. A través de dinámicas psicosociales, se generó un espacio de escucha, respeto y conexión intergeneracional, reafirmando el valor de cada recuerdo como una huella de amor y aprendizaje.

Esta actividad permitió fortalecer vínculos, rescatar la memoria viva y reconocer la importancia de brindar espacios donde las personas mayores se sientan valoradas, escuchadas y acompañadas.', '/images/hero-images/2 foto family-9.webp', '["/images/hero-images/2 foto family-9.webp", "/images/hero-images/cam.jpg", "/images/hero-images/cam1.jpg", "/images/hero-images/cam2.jpg", "/images/hero-images/cam3.jpg"]', NULL, 'Bienestar Social', 'from-purple-500 to-pink-600', '🏛️'),
('Taller de Risoterapia "Aprendamos a Reír Juntos" – Zapallanga', '29 mayo 2025', 2025, 'Family Love realizó el taller de risoterapia en el Centro de Salud de Zapallanga, dirigido a pacientes con diabetes e hipertensión, usando la risa como herramienta terapéutica.', 'En el marco de sus acciones de promoción de la salud integral, Family Love realizó el taller de risoterapia "Aprendamos a reír juntos" en el Centro de Salud de Zapallanga, dirigido a pacientes con diagnóstico de diabetes e hipertensión.

La actividad tuvo como objetivo generar un espacio de bienestar emocional, conexión y participación activa, utilizando la risa como una herramienta terapéutica complementaria. A través de dinámicas guiadas, los participantes lograron experimentar momentos de alivio emocional, fortaleciendo su estado de ánimo y promoviendo una visión integral del cuidado de la salud.

Este taller permitió reforzar la importancia del enfoque psicosocial en la atención de la salud, reconociendo que el bienestar emocional es un componente fundamental para mejorar la calidad de vida de las personas.', '/images/hero-images/taller.webp', '["/images/hero-images/taller.webp"]', NULL, 'Salud y Bienestar', 'from-emerald-500 to-teal-600', '😄'),
('Primer Aniversario de Family Love', '10 julio 2025', 2025, 'Family Love conmemora su primer aniversario celebrando doce meses de trabajo continuo, crecimiento y compromiso con la transformación social.', 'Family Love conmemora su primer aniversario, celebrando doce meses de trabajo continuo desde el nacimiento de un sueño que hoy se consolida como una organización unida por la empatía, el compromiso y la vocación de servicio.

A lo largo de este primer año, Family Love ha crecido gracias al esfuerzo y dedicación de sus voluntarios, equipos internos y jóvenes líderes, quienes han aportado no solo su tiempo, sino también su corazón en cada iniciativa desarrollada.

Family Love es más que una organización: es un espacio de encuentro, apoyo y trabajo colectivo que promueve valores humanos y fortalece vínculos. Este aniversario marca un hito importante y, a la vez, el inicio de nuevos retos y oportunidades para seguir generando impacto positivo en la sociedad.', '/images/hero-images/family love ullusca footo-67.webp', '["/images/hero-images/family love ullusca footo-67.webp", "/images/hero-images/aniversario.jpg", "/images/hero-images/aniversario1.jpg", "/images/hero-images/aniversario2.jpg", "/images/hero-images/aniversario3.jpg"]', NULL, 'Aniversario', 'from-yellow-400 to-orange-500', '🎉'),
('Campaña "Corazones Solidarios" – Albergue Santo Monte de Jehová', '15 agosto 2025', 2025, 'Family Love desarrolló la campaña Corazones Solidarios en el Albergue Santo Monte de Jehová en San Agustín de Cajas, brindando apoyo integral a adultos mayores.', 'En el marco de sus acciones solidarias, Family Love desarrolló la campaña "Corazones Solidarios", una iniciativa orientada a brindar apoyo integral a los adultos mayores del Albergue Santo Monte de Jehová, ubicado en el distrito de San Agustín de Cajas.

Gracias a la participación de la comunidad y al apoyo obtenido a través de la rifa solidaria, fue posible realizar la entrega de donaciones y compartir una jornada de acompañamiento, cuidado y cercanía con los residentes del albergue.

Durante la visita, los voluntarios de Family Love no solo realizaron la entrega de ayuda material, sino que también colaboraron activamente en labores de limpieza, cocina, higiene personal, peinado y cortes de cabello. Asimismo, se preparó y entregó un refrigerio, promoviendo un ambiente de respeto, alegría y trato digno.

Auspiciadores: Joel Oroncoy, Miluscka Makeup, Mr Juerga, Fernix Moda y Rock Centro.', '/images/hero-images/2 foto family-9.webp', '["/images/hero-images/2 foto family-9.webp"]', NULL, 'Campaña Solidaria', 'from-red-400 to-rose-600', '❤️'),
('"Manos que Acompañan" – Segunda Campaña Solidaria en Jauja', '04 setiembre 2025', 2025, 'Family Love llevó a cabo su segunda campaña solidaria en Jauja, brindando apoyo integral a personas adultas mayores, adultos y niños en situación de vulnerabilidad.', 'Family Love llevó a cabo su segunda campaña solidaria denominada "Manos que Acompañan", una jornada orientada a brindar apoyo integral a personas adultas mayores, adultos y niños en situación de calle o vulnerabilidad en la ciudad de Jauja.

Esta actividad fue posible gracias al apoyo de la comunidad y a los recursos obtenidos mediante la rifa solidaria organizada por Family Love, lo que permitió ampliar el alcance de la intervención y llegar a más personas que requieren acompañamiento y atención.

Durante la jornada, los voluntarios compartieron no solo donaciones, sino también tiempo, escucha activa y gestos de cercanía, reafirmando que la ayuda social va más allá de la asistencia material y que acompañar también significa brindar dignidad y contención emocional.

Auspiciadores: Joel Oroncoy, Miluscka Makeup, Mr Juerga, Fernix Moda y Rock Centro.', '/images/hero-images/h2.webp', '["/images/hero-images/h2.webp", "/images/hero-images/solidaridad-jauja.jpg", "/images/hero-images/solidaridad-jauja1.jpg", "/images/hero-images/solidaridad-jauja2.jpg", "/images/hero-images/solidaridad-jauja3.jpg", "/images/hero-images/solidaridad-jauja4.jpg", "/images/hero-images/solidaridad-jauja5.jpg"]', NULL, 'Campaña Solidaria', 'from-blue-400 to-cyan-500', '🤝'),
('Primera Campaña Navideña 2025 – San José de Apata', '27 diciembre 2025', 2025, 'Family Love llevó momentos de alegría y esperanza a la comunidad campesina de San José de Apata en Jauja, en su primera campaña navideña del 2025.', 'Elegir un lugar también significa escuchar realidades diversas. La comunidad campesina de San José de Apata es una zona que históricamente ha enfrentado múltiples necesidades; sin embargo, para Family Love, la distancia no representa un límite cuando existe voluntad de servir y compromiso social.

Esta primera campaña navideña del 2025 tuvo como propósito llevar momentos de alegría, cercanía y esperanza, reafirmando que allí donde exista una necesidad, Family Love estará presente con acciones concretas y solidarias.

Auspiciadores: Colegio San Antonio María Claret, Ancosur Inmobiliaria y la Familia Santo Rojas.', '/images/hero-images/1er-navidad-2025-4.jpg', '["/images/hero-images/1er-navidad-2025.jpg", "/images/hero-images/1er-navidad-2025-1.jpg", "/images/hero-images/1er-navidad-2025-2.jpg", "/images/hero-images/1er-navidad-2025-3.jpg", "/images/hero-images/1er-navidad-2025-4.jpg", "/images/hero-images/1er-navidad-2025-5.jpg"]', '/images/videos/1er-navidad-2025 video-2.mp4', 'Campaña Navideña', 'from-rose-500 to-red-600', '🎄'),
('Segunda Campaña Navideña 2025 – Calles de Huancayo', '30 diciembre 2025', 2025, 'Family Love llevó a cabo su segunda campaña navideña del año en beneficio de adultos mayores y niños en situación de vulnerabilidad en las calles de Huancayo.', 'Family Love llevó a cabo su segunda campaña navideña del año 2025 en beneficio de adultos mayores y niños en situación de vulnerabilidad en las calles de Huancayo.

La intervención tuvo como propósito visibilizar realidades muchas veces olvidadas, escuchar historias que merecen ser atendidas y brindar momentos de cercanía, alegría y acompañamiento a personas que se encuentran en condiciones de alta vulnerabilidad social.

Para Family Love, estar presente en estos espacios reafirma su compromiso de llegar donde más se necesita, generando impacto a través de acciones solidarias y humanas.

Auspiciadores: Colegio San Antonio María Claret, Ancosur Inmobiliaria y la Familia Santo Rojas.', '/images/hero-images/2-navidad-2025-2.jpg', '["/images/hero-images/2-navidad-2025-2.jpg", "/images/hero-images/2-navidad-2025.jpg", "/images/hero-images/2-navidad-2025-3.jpg", "/images/hero-images/2-navidad-2025-4.jpg", "/images/hero-images/2-navidad-2025-5.jpg", "/images/hero-images/2-navidad-2025-6.jpg", "/images/hero-images/2-navidad-2025-7.jpg"]', '/images/videos/1er-navidad-2025 video-1.mp4', 'Campaña Navideña', 'from-indigo-500 to-blue-600', '🎅');
